version: '3'

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
